FROM maven:3.9-eclipse-temurin-21-alpine AS builder

WORKDIR /app

COPY pom.xml .
COPY src ./src

RUN mvn package -DskipTests

FROM eclipse-temurin:21-jdk-alpine

COPY --from=builder /app/target/*.jar production-optimiser-api.jar

CMD ["java", "-jar", "production-optimiser-api.jar"]