name: Frontend React App

#on:
#  push:
#    paths:
#      - frontend/**
#    branches:
#      - main
#      - develop
#
#  pull_request:
#    paths:
#      - frontend/**
#    branches:
#      - main
#      - develop

jobs:
  check-js-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest

      # Run Biome Lint Check
      - name: Run Biome Check
        run: biome check .
        continue-on-error: true # Allow workflow to continue while capturing errors

      # Output Biome Issues if any errors are found
      - name: Output Biome Issues
        if: failure() # This step only runs if the Biome Check fails
        run: |
          echo "Biome found linting errors. Please fix the issues below:"
          biome check .

      # Optional: Auto-Fix Formatting Issues
      - name: Auto-Fix Formatting
        if: failure() # Run auto-fix only if issues are found
        run: biome fmt .
