name: Java Unit Tests

on:
  push:
    paths:
      - backend/**
    branches:
      - develop
      
  pull_request:
    paths:
      - backend/**
    branches:
      - main
      - develop

jobs:
  run-unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend/production-optimiser-api
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Run unit tests
      run: mvn test
