name: Check Java Code Formatting

on:
  push:
    paths:
      - backend/**
    branches:
      - develop
      
  pull_request:
    paths:
      - backend/**
    branches:
      - main
      - develop

jobs:
  check-format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Build and check formatting
      run: mvn spotless:check